from_number:
  display_name: "Phone Number"
  description: "Please enter your twilio phone number with country code (Eg.+13345395652)"
  type: "text"
  required: true
account_sid:
  display_name: "Account SID"
  description: "Please enter your twilio Account SID"
  type: "text"
  required: true
auth_token:
  display_name: "Auth Token"
  description: "Please enter your twilio Auth Token"
  type: "text"
  required: true 
msg_content:
  display_name: "Default Message Content"
  description: "Please enter the default message content"
  type: "text"
  default_value: "Do not reply"
  required: false