from_number:
  display_name: "Twilio Phone Number"
  description: "Please enter your twilio phone number with country code (Eg.+13345395652)"
  type: "text"
  required: true
to_number:
  display_name: "Phone Number to get SMS"
  description: "Please enter your phone number with country code to get SMS (Eg. +918888888888)"
  type: "text"
  required: true
account_sid:
  display_name: "Account SID"
  description: "Please enter your twilio Account SID"
  type: "text"
  required: true
auth_token:
  display_name: "Auth Token"
  description: "Please enter your twilio Auth Token"
  type: "text"
  required: true 
msg_content:
  display_name: "Default Message Content"
  description: "Please enter the default message content"
  type: "text"
  default_value: "Do not reply"
  required: false
domain:
  display_name: "Freshdesk Domain"
  description: "Please enter your Freshdesk domain (Eg: https://domain.freshdesk.com)"
  type: "text"
  required: true