name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello, Thanks for taking the step forward to create an issue that would improve our sample apps. 🙂\n\nThis will be picked up by one of us soon. Watch the issue notifications for updates'
        pr-message: 'Thanks for your contribution to Freshworks sample apps. 🎉\n\nOur maintainers will review your pull request soon.'
