name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for taking a step forward to create an issue and for thinking to improve our sample apps. 🙂\n\nThis will be picked up by any of the contributors soon. Watch the issue notifications for updates.'
        pr-message: 'Thanks for your contribution to our sample apps. 🎉\n\nTake a look at the other issues while the repo maintainers review your Pull Request.'
